### ISSUE TITLE
v0.7.2-beta crashes when recording new track (target api 28/android 9): Missing android.permission.FOREGROUND_SERVICE

### ISSUE THREAD

**Issue by jdmonin** [labexp/osmtracker-android#214]
On android 9, the new beta version crashes when trying to record a track.

Seen on develop 26d720c.  At its parent commit b690ba0, does not crash.

The beta raises target api level to 28.  https://developer.android.com/about/versions/pie/android-9.0-changes-28 confirms: "If an app that targets Android 9 or higher attempts to create a foreground service without requesting FOREGROUND_SERVICE, the system throws a SecurityException."

That matches the logcat output:
```
2019-06-26 06:57:44.795 7444-7444/net.osmtracker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.osmtracker, PID: 7444
    java.lang.RuntimeException: Unable to start service net.osmtracker.service.gps.GPSLogger@cecf2c with Intent { cmp=net.osmtracker/.service.gps.GPSLogger (has extras) }: java.lang.SecurityException: Permission Denial: startForeground from pid=7444, uid=10092 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=7444, uid=10092 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1942)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
        at android.app.Service.startForeground(Service.java:695)
        at net.osmtracker.service.gps.GPSLogger.onStartCommand(GPSLogger.java:233)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by xsaco07** [comment]
The corresponding fix was already merged into develop branch.
Thanks!
